### PR TITLE
fix compilation error with `minifyEnabled=true`

### PR DESCRIPTION
**Pull request by soshial**
WalletConnect BOM 1.32.1 causes compilation error. Adding `-dontwarn groovy.lang.GroovyShell` fixes the problem.

### CODE REVIEW

**Comment by jakubuid** [comment]
Closing in favor of: https://github.com/WalletConnect/WalletConnectKotlinV2/pull/1439

**Comment by soshial** [comment]
Honestly, I completely don't understand, why you created a copy of my PR, and then simply closed mine in favour of yours?

**Comment by jakubuid** [comment]
Oh, I just couldn't make all checks to work on yours so I decided to create a new one, did not mean to offend you, sorry 🙏 
You can re-open and I can merge from yours, if it's ok with you

**Comment by soshial** [comment]
Honestly, it was demotivating to see my contribution be rejected... Thank you for understanding, @jakubuid. I'd be really happy to see my contribution to this lib.

May I ask you to reopen the PR, since I don't have the permission?
(Although, I got several notification that all workflow jobs have failed, although it's identical to yours; would we be able to merge it without those checks passing?)

**Comment by jakubuid** [comment]
Yes, ofc!!!
My bad - I'll figure out another way to test-check. Re-opening!

**Pull request merged**
