### PR TITLE
added suffix const and changed iridium to irn

### PR DESCRIPTION
**Pull request by TalhaAli00**

### CODE REVIEW

**Review by Elyniss — CHANGES_REQUESTED** [review]
I like your approach, however you only applied prefix changes into Chat SDK. Could you also add it to Sign SDK?

**Comment by Elyniss** [comment]
Should we also change the default `protocol` value in `RelayProtocolOptionsVO`?

**Comment by Elyniss** [comment]
`RelayerDOJsonRpcResponseJsonRpcResultJsonAdapterTest` contains "iridium" as well

**Comment by Elyniss** [comment]
I would also rename `IridiumParamsVO` to `IrnParamsVo` with all it's usages

**Comment by Elyniss** [comment]
Also could we remove `Iridium` prefix from `IridiumJWTHeader` and `IridiumJWTPayload` classes

**Review by Elyniss — APPROVED** [review]
LGTM

**Review by jakobuid — APPROVED** [review]

**Pull request merged**
