### PR TITLE
Fix SessionRequestVOJsonAdapter when `params` json has only one field

### PR DESCRIPTION
**Pull request by spartan-thangtranduc**
Fix SessionRequestVOJsonAdapter when `params` json has only one field

Issues:
Screenshot 2024-03-06 at 15 00 18

Fixed:
Screenshot 2024-03-06 at 15 00 43

### CODE REVIEW

**Comment by TalhaAli00** [comment]
@spartan-thangtranduc 
Please revert your changes that aren't related to SessionRequestVOJsonAdapter.kt

**Comment by spartan-thangtranduc** [comment]
Oh sorry, let I revert them

**Review by TalhaAli00 — APPROVED** [review]

**Comment by TalhaAli00** [comment]
@jakubuid do you have any issues with this PR? I've run the changes locally and the tests are working for me

**Comment by jakubuid** [comment]
> @jakubuid do you have any issues with this PR? I've run the changes locally and the tests are working for me

No I don't let's test it manually too and we should be good to merge

**Comment by TalhaAli00** [comment]
@jakubuid I've tested this locally and the samples work for me. If you don't see any issues, then let's merge this in

**Review by jakubuid — APPROVED** [review]

**Pull request merged**
